#!/bin/bash

main () {

	REPOSITORY='/mnt/david-huser-bak'
	export BORG_PASSPHRASE=$(</home/david-w/.config/BORG_PASSPHRASE)

	if grep -qs "$REPOSITORY" /proc/mounts; then
	  echo "$REPOSITORY mounted."
	else
		notify-send -t 10000 $N_TITLE "$REPOSITORY not available"
		exit
	fi

	notify-send -t 10000 "+++ Borg Backup started at $(date +%H:%M) +++"

	OUTPUT=$(borg create -v --stats                 \
		$REPOSITORY::'{hostname}-{now:%Y-%m-%d}'    \
		/home/david-w/                              \
		/etc/                                       \
		--exclude '/home/*/.cache'                  \
		--exclude '*.pyc')


	echo "$OUTPUT"


	# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
	# archives of THIS machine. The '{hostname}-' prefix is very important to
	# limit prune's operation to this machine's archives and not apply to
	# other machine's archives also.
	borg prune -v --list $REPOSITORY --prefix '{hostname}-' \
	    --keep-daily=7 --keep-weekly=4 --keep-monthly=6


	notify-send -t 10000 "+++ Borg Backup finshed. +++"
}

main

