location:
  source_directories:
    - /home/david
  repositories:
    - borgbackup@piero.local:/mnt/backups
  exclude_patterns:
    - '*.pyc'
    - /home/david/.cache
    - '/home/david/VirtualBox VMs'
    - '/home/david/.Genymobile'
  exclude_caches: true
storage:
  compression: lz4
  encryption_passphrase: CHANGEME
  archive_name_format: '{hostname}-{now}'
  ssh_command: ssh -i ~/.ssh/borgbackup
  lock_wait: 600
retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 12
  keep_yearly: 1
  prefix: '{hostname}-'
consistency:
  checks:
    - repository
    - archives
  prefix: '{hostname}-'
  check_last: 3